name: Deploy via SSH

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Try connect ssh
        id: reload_server
  
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "access-5017241429.webspace-host.com"
          username: "a875422"
          password: "calahonda592"
          port: 22
          script: |
            echo "Accediendo a repo"
            ls
